import sys

data = ['TTGCGTCCCGTGCCG', 'GCGGACGTAGTCCCG', 'GCGCTTGATTTCCCG', 'GCGCTCTAAGTCCCG', 'TCGCTTGTAGTCCGA', 'GCGCCCCTAGTCCCG', 'GCGCGATTAGTCCCG', 'GCGCTTGTAGTCAAT', 'GCGCTTGTACGACCG', 'GCGCTGTAAGTCCCG',
        'GCGGGCGTAGTCCCG', 'ATCCTTGTAGTCCCG', 'GCGCTTGTCCGCCCG', 'ATGCTTGTAGTCCCA', 'GCGCTTCATGTCCCG', 'GCGCTTCAGGTCCCG', 'GCGCTTGTAGTATTG', 'GAAATTGTAGTCCCG', 'GCCTGTGTAGTCCCG', 'GCGCTTGTAGCGTCG']


def listtoans(somelist):
    with open(sys.argv[1], "w")as f:
        for item in somelist:
            f.write(item+'\n')


listtoans(data)
